In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
# load the data
train_df = pd.read_csv("../dataset/train_clean.csv")
test_df = pd.read_csv("../dataset/test_clean.csv")

In [20]:
test_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,is_tsh_missing,is_year_missing,is_pop_missing,is_coord_missing,...,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other,geo_cluster,pump_age,geo_source_te,geo_source_freq
0,3.931826,1996.0,35.290799,-4.059696,5.774552,2012.0,1,0,0,0,...,0,0,0,0,0,1,9,1.0,0.640050,0.523685
1,3.044522,1569.0,36.656709,-3.309214,5.707110,2000.0,1,0,0,0,...,1,0,0,0,0,0,0,13.0,0.675847,9.818672
2,3.931826,1567.0,34.767863,-5.004344,6.216606,2010.0,1,0,0,0,...,0,0,0,0,0,1,9,3.0,0.640050,0.523685
3,3.931826,267.0,38.058046,-9.418672,5.525453,1987.0,1,0,0,0,...,0,0,0,0,0,1,3,26.0,1.605582,1.731402
4,6.216606,1260.0,35.006123,-10.950412,4.110874,2000.0,0,0,0,0,...,1,0,0,0,0,0,2,13.0,0.803993,1.465295

In [21]:
train_df.head()

,amount_tsh,gps_height,longitude,latitude,population,construction_year,status_group,is_tsh_missing,is_year_missing,is_pop_missing,...,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other,geo_cluster,pump_age,geo_source_te,geo_source_freq
0,8.699681,1390.0,34.938093,-9.856322,4.700480,1999.0,functional,0,0,0,...,1,0,0,0,0,0,2,12.0,0.810144,1.465295
1,4.615121,1399.0,34.698766,-2.147466,5.638355,2010.0,functional,1,0,0,...,1,0,0,0,0,0,6,3.0,0.669483,0.564625
2,3.258097,686.0,37.460664,-3.821329,5.525453,2009.0,functional,0,0,0,...,0,1,0,0,0,0,0,4.0,0.812285,0.049469
3,3.931826,263.0,38.486161,-11.155298,4.077537,1986.0,non functional,1,0,0,...,0,1,0,0,0,0,3,27.0,1.185000,2.725893
4,5.525453,1189.0,31.130847,-1.825359,5.303305,1986.0,functional,1,1,1,...,1,0,0,0,0,0,11,25.0,0.607714,0.639681

In [22]:
# because some tree models do not accept spaces in column names
train_df.columns = train_df.columns.str.replace(" ", "_")
test_df.columns = test_df.columns.str.replace(" ", "_")

In [23]:
set(train_df.columns.tolist())-(set(test_df.columns.tolist()))

{'status_group'}

In [24]:
y = train_df["status_group"]
X = train_df.drop(["status_group"], axis=1)

In [25]:
test_df.isnull().sum()

amount_tsh               0
gps_height               0
longitude                0
latitude                 0
population               0
                        ..
waterpoint_type_other    0
geo_cluster              0
pump_age                 0
geo_source_te            0
geo_source_freq          0
Length: 138, dtype: int64

In [26]:
train_df.isnull().sum()

amount_tsh               0
gps_height               0
longitude                0
latitude                 0
population               0
                        ..
waterpoint_type_other    0
geo_cluster              0
pump_age                 0
geo_source_te            0
geo_source_freq          0
Length: 139, dtype: int64

In [27]:
X.shape

(58623, 138)

In [28]:
test_df.shape

(14850, 138)

In [29]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=["status_group"])
y = train_df["status_group"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# lets train a random forest model
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators = 500, 
    max_depth = None,
    min_samples_split = 5,
    min_samples_leaf = 2,
    max_features = "sqrt",
    bootstrap = True,
    random_state = 42,
    n_jobs = -1,
    class_weight = "balanced"
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(min_samples_leaf=2, min_samples_split=5,
                       n_estimators=500, n_jobs=-1, random_state=42)

In [31]:
rf_model_preds = rf_model.predict(X_val)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_val, rf_model_preds))
print(confusion_matrix(y_val, rf_model_preds))
print(accuracy_score(y_val, rf_model_preds))

                         precision    recall  f1-score   support

             functional       0.79      0.91      0.85      6364
functional needs repair       0.63      0.24      0.34       838
         non functional       0.84      0.77      0.80      4523

               accuracy                           0.81     11725
              macro avg       0.75      0.64      0.67     11725
           weighted avg       0.80      0.81      0.79     11725

[[5784   71  509]
 [ 509  199  130]
 [1003   48 3472]]
0.8063965884861407

In [32]:
rf_model_preds = rf_model.predict(test_df)
rf_model_preds

array(['functional', 'functional', 'functional', ..., 'functional',
       'functional', 'non functional'], shape=(14850,), dtype=object)

In [ ]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=0.1,       # L1
    reg_lambda=1.0,      # L2
    objective='multi:softmax',
    num_class=3,
    eval_metric='mlogloss',
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1,
    device='cuda',
    class_weight='balanced'
)

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y_train)
y_val_encoded = le.transform(y_val)


xgb_model.fit(X_train, y_encoded, 
              eval_set=[(X_val, y_val_encoded)])

[0]	validation_0-mlogloss:0.86957
[1]	validation_0-mlogloss:0.85509
[2]	validation_0-mlogloss:0.84046
[3]	validation_0-mlogloss:0.82703
[4]	validation_0-mlogloss:0.81416
[5]	validation_0-mlogloss:0.80278
[6]	validation_0-mlogloss:0.79144
[7]	validation_0-mlogloss:0.78110
[8]	validation_0-mlogloss:0.77142
[9]	validation_0-mlogloss:0.76263
[10]	validation_0-mlogloss:0.75439
[11]	validation_0-mlogloss:0.74657
[12]	validation_0-mlogloss:0.73958
[13]	validation_0-mlogloss:0.73240
[14]	validation_0-mlogloss:0.72610
[15]	validation_0-mlogloss:0.72027
[16]	validation_0-mlogloss:0.71456
[17]	validation_0-mlogloss:0.70914
[18]	validation_0-mlogloss:0.70400
[19]	validation_0-mlogloss:0.69925
[20]	validation_0-mlogloss:0.69475
[21]	validation_0-mlogloss:0.69059
[22]	validation_0-mlogloss:0.68657
[23]	validation_0-mlogloss:0.68280
[24]	validation_0-mlogloss:0.67922
[25]	validation_0-mlogloss:0.67566
[26]	validation_0-mlogloss:0.67223
[27]	validation_0-mlogloss:0.66894
[28]	validation_0-mlogloss:0.66613
[29]	validation_0-mlogloss:0.66308
[30]	validation_0-mlogloss:0.66008
[31]	validation_0-mlogloss:0.65727
[32]	validation_0-mlogloss:0.65453
[33]	validation_0-mlogloss:0.65220
[34]	validation_0-mlogloss:0.64984
[35]	validation_0-mlogloss:0.64774
[36]	validation_0-mlogloss:0.64528
[37]	validation_0-mlogloss:0.64287
[38]	validation_0-mlogloss:0.64046
[39]	validation_0-mlogloss:0.63861
[40]	validation_0-mlogloss:0.63654
[41]	validation_0-mlogloss:0.63468
[42]	validation_0-mlogloss:0.63288
[43]	validation_0-mlogloss:0.63081
[44]	validation_0-mlogloss:0.62900
[45]	validation_0-mlogloss:0.62721
[46]	validation_0-mlogloss:0.62558
[47]	validation_0-mlogloss:0.62394
[48]	validation_0-mlogloss:0.62235
[49]	validation_0-mlogloss:0.62094
[50]	validation_0-mlogloss:0.61935
[51]	validation_0-mlogloss:0.61791
[52]	validation_0-mlogloss:0.61677
[53]	validation_0-mlogloss:0.61550
[54]	validation_0-mlogloss:0.61426
[55]	validation_0-mlogloss:0.61292
[56]	validation_0-mlogloss:0.61151
[57]	validation_0-mlogloss:0.61036
[58]	validation_0-mlogloss:0.60927
[59]	validation_0-mlogloss:0.60834
[60]	validation_0-mlogloss:0.60722
[61]	validation_0-mlogloss:0.60624
[62]	validation_0-mlogloss:0.60524
[63]	validation_0-mlogloss:0.60423
[64]	validation_0-mlogloss:0.60302
[65]	validation_0-mlogloss:0.60204
[66]	validation_0-mlogloss:0.60122
[67]	validation_0-mlogloss:0.60030
[68]	validation_0-mlogloss:0.59945
[69]	validation_0-mlogloss:0.59854
[70]	validation_0-mlogloss:0.59765
[71]	validation_0-mlogloss:0.59679
[72]	validation_0-mlogloss:0.59602
[73]	validation_0-mlogloss:0.59513
[74]	validation_0-mlogloss:0.59424
[75]	validation_0-mlogloss:0.59349
[76]	validation_0-mlogloss:0.59260
[77]	validation_0-mlogloss:0.59178
[78]	validation_0-mlogloss:0.59110
[79]	validation_0-mlogloss:0.59038
[80]	validation_0-mlogloss:0.58974
[81]	validation_0-mlogloss:0.58904
[82]	validation_0-mlogloss:0.58831
[83]	validation_0-mlogloss:0.58758
[84]	validation_0-mlogloss:0.58686
[85]	validation_0-mlogloss:0.58618
[86]	validation_0-mlogloss:0.58559
[87]	validation_0-mlogloss:0.58487
[88]	validation_0-mlogloss:0.58438
[89]	validation_0-mlogloss:0.58396
[90]	validation_0-mlogloss:0.58325
[91]	validation_0-mlogloss:0.58278
[92]	validation_0-mlogloss:0.58235
[93]	validation_0-mlogloss:0.58178
[94]	validation_0-mlogloss:0.58135
[95]	validation_0-mlogloss:0.58062
[96]	validation_0-mlogloss:0.58014
[97]	validation_0-mlogloss:0.57950
[98]	validation_0-mlogloss:0.57900
[99]	validation_0-mlogloss:0.57847
[100]	validation_0-mlogloss:0.57787
[101]	validation_0-mlogloss:0.57750
[102]	validation_0-mlogloss:0.57702
[103]	validation_0-mlogloss:0.57643
[104]	validation_0-mlogloss:0.57605
[105]	validation_0-mlogloss:0.57551
[106]	validation_0-mlogloss:0.57500
[107]	validation_0-mlogloss:0.57440
[108]	validation_0-mlogloss:0.57399
[109]	validation_0-mlogloss:0.57352
[110]	validation_0-mlogloss:0.57322
[111]	validation_0-mlogloss:0.57280
[112]	validation_0-mlogloss:0.57248
[113]	validation_0-mlogloss:0.57209
[114]	validation_0-mlogloss:0.57178
[115]	validation_0-mlogloss:0.57149
[116]	validation_0-mlogloss:0.57114
[117]	validation_0-mlogloss:0.57075
[118]	validation_0-mlogloss:0.57044
[119]	validation_0-mlogloss:0.57011
[120]	validation_0-mlogloss:0.56965
[121]	validation_0-mlogloss:0.56921
[122]	validation_0-mlogloss:0.56886
[123]	validation_0-mlogloss:0.56846
[124]	validation_0-mlogloss:0.56784
[125]	validation_0-mlogloss:0.56743
[126]	validation_0-mlogloss:0.56705
[127]	validation_0-mlogloss:0.56681
[128]	validation_0-mlogloss:0.56642
[129]	validation_0-mlogloss:0.56619
[130]	validation_0-mlogloss:0.56593
[131]	validation_0-mlogloss:0.56550
[132]	validation_0-mlogloss:0.56513
[133]	validation_0-mlogloss:0.56476
[134]	validation_0-mlogloss:0.56447
[135]	validation_0-mlogloss:0.56405
[136]	validation_0-mlogloss:0.56379
[137]	validation_0-mlogloss:0.56334
[138]	validation_0-mlogloss:0.56306
[139]	validation_0-mlogloss:0.56280
[140]	validation_0-mlogloss:0.56254
[141]	validation_0-mlogloss:0.56227
[142]	validation_0-mlogloss:0.56200
[143]	validation_0-mlogloss:0.56172
[144]	validation_0-mlogloss:0.56139
[145]	validation_0-mlogloss:0.56120
[146]	validation_0-mlogloss:0.56061
[147]	validation_0-mlogloss:0.56035
[148]	validation_0-mlogloss:0.56003
[149]	validation_0-mlogloss:0.55980
[150]	validation_0-mlogloss:0.55951
[151]	validation_0-mlogloss:0.55921
[152]	validation_0-mlogloss:0.55893
[153]	validation_0-mlogloss:0.55866
[154]	validation_0-mlogloss:0.55826
[155]	validation_0-mlogloss:0.55800
[156]	validation_0-mlogloss:0.55773
[157]	validation_0-mlogloss:0.55750
[158]	validation_0-mlogloss:0.55727
[159]	validation_0-mlogloss:0.55704
[160]	validation_0-mlogloss:0.55675
[161]	validation_0-mlogloss:0.55650
[162]	validation_0-mlogloss:0.55633
[163]	validation_0-mlogloss:0.55607
[164]	validation_0-mlogloss:0.55575
[165]	validation_0-mlogloss:0.55547
[166]	validation_0-mlogloss:0.55529
[167]	validation_0-mlogloss:0.55506
[168]	validation_0-mlogloss:0.55487
[169]	validation_0-mlogloss:0.55475
[170]	validation_0-mlogloss:0.55456
[171]	validation_0-mlogloss:0.55429
[172]	validation_0-mlogloss:0.55407
[173]	validation_0-mlogloss:0.55390
[174]	validation_0-mlogloss:0.55370
[175]	validation_0-mlogloss:0.55351
[176]	validation_0-mlogloss:0.55329
[177]	validation_0-mlogloss:0.55298
[178]	validation_0-mlogloss:0.55282
[179]	validation_0-mlogloss:0.55259
[180]	validation_0-mlogloss:0.55239
[181]	validation_0-mlogloss:0.55221
[182]	validation_0-mlogloss:0.55195
[183]	validation_0-mlogloss:0.55166
[184]	validation_0-mlogloss:0.55148
[185]	validation_0-mlogloss:0.55134
[186]	validation_0-mlogloss:0.55111
[187]	validation_0-mlogloss:0.55088
[188]	validation_0-mlogloss:0.55067
[189]	validation_0-mlogloss:0.55050
[190]	validation_0-mlogloss:0.55028
[191]	validation_0-mlogloss:0.55017
[192]	validation_0-mlogloss:0.54992
[193]	validation_0-mlogloss:0.54964
[194]	validation_0-mlogloss:0.54927
[195]	validation_0-mlogloss:0.54913
[196]	validation_0-mlogloss:0.54888
[197]	validation_0-mlogloss:0.54861
[198]	validation_0-mlogloss:0.54843
[199]	validation_0-mlogloss:0.54816
[200]	validation_0-mlogloss:0.54791
[201]	validation_0-mlogloss:0.54769
[202]	validation_0-mlogloss:0.54754
[203]	validation_0-mlogloss:0.54741
[204]	validation_0-mlogloss:0.54714
[205]	validation_0-mlogloss:0.54699
[206]	validation_0-mlogloss:0.54687
[207]	validation_0-mlogloss:0.54670
[208]	validation_0-mlogloss:0.54647
[209]	validation_0-mlogloss:0.54633
[210]	validation_0-mlogloss:0.54621
[211]	validation_0-mlogloss:0.54593
[212]	validation_0-mlogloss:0.54561
[213]	validation_0-mlogloss:0.54533
[214]	validation_0-mlogloss:0.54511
[215]	validation_0-mlogloss:0.54491
[216]	validation_0-mlogloss:0.54478
[217]	validation_0-mlogloss:0.54453
[218]	validation_0-mlogloss:0.54440
[219]	validation_0-mlogloss:0.54420
[220]	validation_0-mlogloss:0.54399
[221]	validation_0-mlogloss:0.54383
[222]	validation_0-mlogloss:0.54356
[223]	validation_0-mlogloss:0.54344
[224]	validation_0-mlogloss:0.54332
[225]	validation_0-mlogloss:0.54317
[226]	validation_0-mlogloss:0.54299
[227]	validation_0-mlogloss:0.54288
[228]	validation_0-mlogloss:0.54274
[229]	validation_0-mlogloss:0.54259
[230]	validation_0-mlogloss:0.54241
[231]	validation_0-mlogloss:0.54219
[232]	validation_0-mlogloss:0.54188
[233]	validation_0-mlogloss:0.54162
[234]	validation_0-mlogloss:0.54141
[235]	validation_0-mlogloss:0.54127
[236]	validation_0-mlogloss:0.54108
[237]	validation_0-mlogloss:0.54095
[238]	validation_0-mlogloss:0.54057
[239]	validation_0-mlogloss:0.54039
[240]	validation_0-mlogloss:0.54026
[241]	validation_0-mlogloss:0.54015
[242]	validation_0-mlogloss:0.53995
[243]	validation_0-mlogloss:0.53979
[244]	validation_0-mlogloss:0.53963
[245]	validation_0-mlogloss:0.53955
[246]	validation_0-mlogloss:0.53938
[247]	validation_0-mlogloss:0.53920
[248]	validation_0-mlogloss:0.53901
[249]	validation_0-mlogloss:0.53892
[250]	validation_0-mlogloss:0.53865
[251]	validation_0-mlogloss:0.53850
[252]	validation_0-mlogloss:0.53835
[253]	validation_0-mlogloss:0.53819
[254]	validation_0-mlogloss:0.53798
[255]	validation_0-mlogloss:0.53787
[256]	validation_0-mlogloss:0.53772
[257]	validation_0-mlogloss:0.53755
[258]	validation_0-mlogloss:0.53739
[259]	validation_0-mlogloss:0.53723
[260]	validation_0-mlogloss:0.53715
[261]	validation_0-mlogloss:0.53705
[262]	validation_0-mlogloss:0.53690
[263]	validation_0-mlogloss:0.53672
[264]	validation_0-mlogloss:0.53652
[265]	validation_0-mlogloss:0.53632
[266]	validation_0-mlogloss:0.53621
[267]	validation_0-mlogloss:0.53607
[268]	validation_0-mlogloss:0.53597
[269]	validation_0-mlogloss:0.53584
[270]	validation_0-mlogloss:0.53568
[271]	validation_0-mlogloss:0.53554
[272]	validation_0-mlogloss:0.53544
[273]	validation_0-mlogloss:0.53530
[274]	validation_0-mlogloss:0.53513
[275]	validation_0-mlogloss:0.53492
[276]	validation_0-mlogloss:0.53483
[277]	validation_0-mlogloss:0.53467
[278]	validation_0-mlogloss:0.53455
[279]	validation_0-mlogloss:0.53433
[280]	validation_0-mlogloss:0.53419
[281]	validation_0-mlogloss:0.53397
[282]	validation_0-mlogloss:0.53389
[283]	validation_0-mlogloss:0.53375
[284]	validation_0-mlogloss:0.53371
[285]	validation_0-mlogloss:0.53360
[286]	validation_0-mlogloss:0.53336
[287]	validation_0-mlogloss:0.53318
[288]	validation_0-mlogloss:0.53308
[289]	validation_0-mlogloss:0.53301
[290]	validation_0-mlogloss:0.53291
[291]	validation_0-mlogloss:0.53277
[292]	validation_0-mlogloss:0.53252
[293]	validation_0-mlogloss:0.53231
[294]	validation_0-mlogloss:0.53219
[295]	validation_0-mlogloss:0.53208
[296]	validation_0-mlogloss:0.53196
[297]	validation_0-mlogloss:0.53180
[298]	validation_0-mlogloss:0.53168
[299]	validation_0-mlogloss:0.53153
[300]	validation_0-mlogloss:0.53145
[301]	validation_0-mlogloss:0.53140
[302]	validation_0-mlogloss:0.53117
[303]	validation_0-mlogloss:0.53100
[304]	validation_0-mlogloss:0.53086
[305]	validation_0-mlogloss:0.53077
[306]	validation_0-mlogloss:0.53060
[307]	validation_0-mlogloss:0.53039
[308]	validation_0-mlogloss:0.53028
[309]	validation_0-mlogloss:0.53015
[310]	validation_0-mlogloss:0.53001
[311]	validation_0-mlogloss:0.52989
[312]	validation_0-mlogloss:0.52975
[313]	validation_0-mlogloss:0.52964
[314]	validation_0-mlogloss:0.52954
[315]	validation_0-mlogloss:0.52942
[316]	validation_0-mlogloss:0.52939
[317]	validation_0-mlogloss:0.52932
[318]	validation_0-mlogloss:0.52917
[319]	validation_0-mlogloss:0.52895
[320]	validation_0-mlogloss:0.52886
[321]	validation_0-mlogloss:0.52881
[322]	validation_0-mlogloss:0.52862
[323]	validation_0-mlogloss:0.52851
[324]	validation_0-mlogloss:0.52838
[325]	validation_0-mlogloss:0.52823
[326]	validation_0-mlogloss:0.52806
[327]	validation_0-mlogloss:0.52782
[328]	validation_0-mlogloss:0.52765
[329]	validation_0-mlogloss:0.52754
[330]	validation_0-mlogloss:0.52744
[331]	validation_0-mlogloss:0.52737
[332]	validation_0-mlogloss:0.52727
[333]	validation_0-mlogloss:0.52718
[334]	validation_0-mlogloss:0.52710
[335]	validation_0-mlogloss:0.52708
[336]	validation_0-mlogloss:0.52696
[337]	validation_0-mlogloss:0.52693
[338]	validation_0-mlogloss:0.52679
[339]	validation_0-mlogloss:0.52671
[340]	validation_0-mlogloss:0.52661
[341]	validation_0-mlogloss:0.52641
[342]	validation_0-mlogloss:0.52628
[343]	validation_0-mlogloss:0.52618
[344]	validation_0-mlogloss:0.52605
[345]	validation_0-mlogloss:0.52586
[346]	validation_0-mlogloss:0.52582
[347]	validation_0-mlogloss:0.52570
[348]	validation_0-mlogloss:0.52559
[349]	validation_0-mlogloss:0.52552
[350]	validation_0-mlogloss:0.52546
[351]	validation_0-mlogloss:0.52537
[352]	validation_0-mlogloss:0.52527
[353]	validation_0-mlogloss:0.52510
[354]	validation_0-mlogloss:0.52499
[355]	validation_0-mlogloss:0.52492
[356]	validation_0-mlogloss:0.52478
[357]	validation_0-mlogloss:0.52474
[358]	validation_0-mlogloss:0.52458
[359]	validation_0-mlogloss:0.52453
[360]	validation_0-mlogloss:0.52442
[361]	validation_0-mlogloss:0.52430
[362]	validation_0-mlogloss:0.52425
[363]	validation_0-mlogloss:0.52408
[364]	validation_0-mlogloss:0.52400
[365]	validation_0-mlogloss:0.52395
[366]	validation_0-mlogloss:0.52387
[367]	validation_0-mlogloss:0.52376
[368]	validation_0-mlogloss:0.52372
[369]	validation_0-mlogloss:0.52356
[370]	validation_0-mlogloss:0.52348
[371]	validation_0-mlogloss:0.52339
[372]	validation_0-mlogloss:0.52334
[373]	validation_0-mlogloss:0.52326
[374]	validation_0-mlogloss:0.52316
[375]	validation_0-mlogloss:0.52309
[376]	validation_0-mlogloss:0.52292
[377]	validation_0-mlogloss:0.52276
[378]	validation_0-mlogloss:0.52271
[379]	validation_0-mlogloss:0.52252
[380]	validation_0-mlogloss:0.52246
[381]	validation_0-mlogloss:0.52235
[382]	validation_0-mlogloss:0.52219
[383]	validation_0-mlogloss:0.52213
[384]	validation_0-mlogloss:0.52205
[385]	validation_0-mlogloss:0.52198
[386]	validation_0-mlogloss:0.52186
[387]	validation_0-mlogloss:0.52175
[388]	validation_0-mlogloss:0.52162
[389]	validation_0-mlogloss:0.52146
[390]	validation_0-mlogloss:0.52139
[391]	validation_0-mlogloss:0.52134
[392]	validation_0-mlogloss:0.52125
[393]	validation_0-mlogloss:0.52118
[394]	validation_0-mlogloss:0.52104
[395]	validation_0-mlogloss:0.52099
[396]	validation_0-mlogloss:0.52093
[397]	validation_0-mlogloss:0.52081
[398]	validation_0-mlogloss:0.52073
[399]	validation_0-mlogloss:0.52070
[400]	validation_0-mlogloss:0.52065
[401]	validation_0-mlogloss:0.52054
[402]	validation_0-mlogloss:0.52046
[403]	validation_0-mlogloss:0.52034
[404]	validation_0-mlogloss:0.52033
[405]	validation_0-mlogloss:0.52013
[406]	validation_0-mlogloss:0.52008
[407]	validation_0-mlogloss:0.52001
[408]	validation_0-mlogloss:0.51993
[409]	validation_0-mlogloss:0.51983
[410]	validation_0-mlogloss:0.51975
[411]	validation_0-mlogloss:0.51966
[412]	validation_0-mlogloss:0.51957
[413]	validation_0-mlogloss:0.51957
[414]	validation_0-mlogloss:0.51952
[415]	validation_0-mlogloss:0.51941
[416]	validation_0-mlogloss:0.51931
[417]	validation_0-mlogloss:0.51922
[418]	validation_0-mlogloss:0.51919
[419]	validation_0-mlogloss:0.51917
[420]	validation_0-mlogloss:0.51911
[421]	validation_0-mlogloss:0.51897
[422]	validation_0-mlogloss:0.51885
[423]	validation_0-mlogloss:0.51875
[424]	validation_0-mlogloss:0.51870
[425]	validation_0-mlogloss:0.51862
[426]	validation_0-mlogloss:0.51849
[427]	validation_0-mlogloss:0.51844
[428]	validation_0-mlogloss:0.51828
[429]	validation_0-mlogloss:0.51820
[430]	validation_0-mlogloss:0.51806
[431]	validation_0-mlogloss:0.51801
[432]	validation_0-mlogloss:0.51793
[433]	validation_0-mlogloss:0.51787
[434]	validation_0-mlogloss:0.51777
[435]	validation_0-mlogloss:0.51770
[436]	validation_0-mlogloss:0.51759
[437]	validation_0-mlogloss:0.51752
[438]	validation_0-mlogloss:0.51744
[439]	validation_0-mlogloss:0.51735
[440]	validation_0-mlogloss:0.51719
[441]	validation_0-mlogloss:0.51705
[442]	validation_0-mlogloss:0.51696
[443]	validation_0-mlogloss:0.51689
[444]	validation_0-mlogloss:0.51678
[445]	validation_0-mlogloss:0.51666
[446]	validation_0-mlogloss:0.51660
[447]	validation_0-mlogloss:0.51649
[448]	validation_0-mlogloss:0.51636
[449]	validation_0-mlogloss:0.51631
[450]	validation_0-mlogloss:0.51626
[451]	validation_0-mlogloss:0.51616
[452]	validation_0-mlogloss:0.51610
[453]	validation_0-mlogloss:0.51600
[454]	validation_0-mlogloss:0.51587
[455]	validation_0-mlogloss:0.51581
[456]	validation_0-mlogloss:0.51576
[457]	validation_0-mlogloss:0.51571
[458]	validation_0-mlogloss:0.51564
[459]	validation_0-mlogloss:0.51558
[460]	validation_0-mlogloss:0.51553
[461]	validation_0-mlogloss:0.51545
[462]	validation_0-mlogloss:0.51536
[463]	validation_0-mlogloss:0.51526
[464]	validation_0-mlogloss:0.51521
[465]	validation_0-mlogloss:0.51513
[466]	validation_0-mlogloss:0.51507
[467]	validation_0-mlogloss:0.51495
[468]	validation_0-mlogloss:0.51485
[469]	validation_0-mlogloss:0.51477
[470]	validation_0-mlogloss:0.51464
[471]	validation_0-mlogloss:0.51452
[472]	validation_0-mlogloss:0.51434
[473]	validation_0-mlogloss:0.51423
[474]	validation_0-mlogloss:0.51417
[475]	validation_0-mlogloss:0.51407
[476]	validation_0-mlogloss:0.51393
[477]	validation_0-mlogloss:0.51386
[478]	validation_0-mlogloss:0.51379
[479]	validation_0-mlogloss:0.51365
[480]	validation_0-mlogloss:0.51354
[481]	validation_0-mlogloss:0.51347
[482]	validation_0-mlogloss:0.51342
[483]	validation_0-mlogloss:0.51337
[484]	validation_0-mlogloss:0.51333
[485]	validation_0-mlogloss:0.51318
[486]	validation_0-mlogloss:0.51314
[487]	validation_0-mlogloss:0.51304
[488]	validation_0-mlogloss:0.51300
[489]	validation_0-mlogloss:0.51296
[490]	validation_0-mlogloss:0.51288
[491]	validation_0-mlogloss:0.51275
[492]	validation_0-mlogloss:0.51267
[493]	validation_0-mlogloss:0.51263
[494]	validation_0-mlogloss:0.51257
[495]	validation_0-mlogloss:0.51241
[496]	validation_0-mlogloss:0.51236
[497]	validation_0-mlogloss:0.51228
[498]	validation_0-mlogloss:0.51218
[499]	validation_0-mlogloss:0.51212
[500]	validation_0-mlogloss:0.51206
[501]	validation_0-mlogloss:0.51197
[502]	validation_0-mlogloss:0.51184
[503]	validation_0-mlogloss:0.51181
[504]	validation_0-mlogloss:0.51170
[505]	validation_0-mlogloss:0.51162
[506]	validation_0-mlogloss:0.51154
[507]	validation_0-mlogloss:0.51144
[508]	validation_0-mlogloss:0.51134
[509]	validation_0-mlogloss:0.51131
[510]	validation_0-mlogloss:0.51121
[511]	validation_0-mlogloss:0.51108
[512]	validation_0-mlogloss:0.51105
[513]	validation_0-mlogloss:0.51099
[514]	validation_0-mlogloss:0.51093
[515]	validation_0-mlogloss:0.51092
[516]	validation_0-mlogloss:0.51094
[517]	validation_0-mlogloss:0.51087
[518]	validation_0-mlogloss:0.51075
[519]	validation_0-mlogloss:0.51071
[520]	validation_0-mlogloss:0.51065
[521]	validation_0-mlogloss:0.51054
[522]	validation_0-mlogloss:0.51044
[523]	validation_0-mlogloss:0.51037
[524]	validation_0-mlogloss:0.51026
[525]	validation_0-mlogloss:0.51023
[526]	validation_0-mlogloss:0.51021
[527]	validation_0-mlogloss:0.51012
[528]	validation_0-mlogloss:0.51013
[529]	validation_0-mlogloss:0.51002
[530]	validation_0-mlogloss:0.50998
[531]	validation_0-mlogloss:0.50993
[532]	validation_0-mlogloss:0.50991
[533]	validation_0-mlogloss:0.50980
[534]	validation_0-mlogloss:0.50973
[535]	validation_0-mlogloss:0.50958
[536]	validation_0-mlogloss:0.50950
[537]	validation_0-mlogloss:0.50939
[538]	validation_0-mlogloss:0.50930
[539]	validation_0-mlogloss:0.50921
[540]	validation_0-mlogloss:0.50908
[541]	validation_0-mlogloss:0.50902
[542]	validation_0-mlogloss:0.50895
[543]	validation_0-mlogloss:0.50887
[544]	validation_0-mlogloss:0.50878
[545]	validation_0-mlogloss:0.50872
[546]	validation_0-mlogloss:0.50862
[547]	validation_0-mlogloss:0.50860
[548]	validation_0-mlogloss:0.50852
[549]	validation_0-mlogloss:0.50846
[550]	validation_0-mlogloss:0.50842
[551]	validation_0-mlogloss:0.50839
[552]	validation_0-mlogloss:0.50832
[553]	validation_0-mlogloss:0.50826
[554]	validation_0-mlogloss:0.50823
[555]	validation_0-mlogloss:0.50816
[556]	validation_0-mlogloss:0.50813
[557]	validation_0-mlogloss:0.50808

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device='cuda', early_stopping_rounds=50,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=-1, num_class=3, ...)

In [35]:
xgb_model_preds = xgb_model.predict(X_val)
print(classification_report(y_val_encoded, xgb_model_preds))
print(confusion_matrix(y_val_encoded, xgb_model_preds))
print(accuracy_score(y_val_encoded, xgb_model_preds))

c:\Users\omaro\OneDrive\Desktop\Study\Kaggle Competitions\pump_it_up_competition\venv\Lib\site-packages\xgboost\core.py:751: UserWarning: [03:12:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

              precision    recall  f1-score   support

           0       0.79      0.90      0.84      6364
           1       0.60      0.25      0.35       838
           2       0.84      0.76      0.80      4523

    accuracy                           0.80     11725
   macro avg       0.74      0.64      0.66     11725
weighted avg       0.79      0.80      0.79     11725

[[5753   85  526]
 [ 506  208  124]
 [1045   53 3425]]
0.8005117270788913

In [36]:
# now let me try the lgbm model
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,

    num_leaves=64,
    max_depth=-1,

    min_data_in_leaf=20,   # ONLY this (not min_child_samples)
    min_gain_to_split=0.0, # ONLY this (not min_split_gain)

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=42
)

lgbm_model.fit(X_train, y_encoded,
              eval_set=[(X_val, y_val_encoded)])

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001703 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1804
[LightGBM] [Info] Number of data points in the train set: 46898, number of used features: 135
[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
[LightGBM] [Info] Start training from score -0.611102
[LightGBM] [Info] Start training from score -2.638120
[LightGBM] [Info] Start training from score -0.952560

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, min_data_in_leaf=20,
               min_gain_to_split=0.0, n_estimators=500, num_leaves=64,
               random_state=42, subsample=0.8)

In [37]:
lgbm_preds = lgbm_model.predict(X_val)
print(classification_report(y_val_encoded, lgbm_preds)) #type: ignore
print(confusion_matrix(y_val_encoded, lgbm_preds))  #type: ignore
print(accuracy_score(y_val_encoded, lgbm_preds))    #type: ignore

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0
              precision    recall  f1-score   support

           0       0.79      0.90      0.84      6364
           1       0.55      0.25      0.34       838
           2       0.84      0.76      0.80      4523

    accuracy                           0.80     11725
   macro avg       0.73      0.64      0.66     11725
weighted avg       0.79      0.80      0.79     11725

[[5715  118  531]
 [ 509  210  119]
 [1037   54 3432]]
0.7980383795309168

In [38]:
from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation='relu',
    solver='adam',
    max_iter=200,
    random_state=42
)

mlp_model.fit(X_train, y_encoded)

MLPClassifier(hidden_layer_sizes=(128, 64), random_state=42)

In [39]:
mlp_preds = mlp_model.predict(X_val)
print(classification_report(y_val_encoded, mlp_preds)) #type: ignore
print(confusion_matrix(y_val_encoded, mlp_preds))  #type: ignore
print(accuracy_score(y_val_encoded, mlp_preds))    #type: ignore

              precision    recall  f1-score   support

           0       0.71      0.93      0.80      6364
           1       0.10      0.00      0.00       838
           2       0.82      0.61      0.70      4523

    accuracy                           0.74     11725
   macro avg       0.54      0.51      0.50     11725
weighted avg       0.71      0.74      0.70     11725

[[5897    2  465]
 [ 701    1  136]
 [1765    7 2751]]
0.7376545842217485

In [115]:
test_ids = pd.read_csv('../dataset/test_ids.csv')['id']

In [117]:
# lets create a submission file for the lgbm model
lgbm_test_preds = lgbm_model.predict(test_df)
submission_df = pd.DataFrame({
    "id": test_ids,
    "status_group": le.inverse_transform(lgbm_test_preds)   #type: ignore
})

[LightGBM] [Warning] min_data_in_leaf is set=20, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=20
[LightGBM] [Warning] min_gain_to_split is set=0.0, min_split_gain=0.0 will be ignored. Current value: min_gain_to_split=0.0

In [ ]:
submission_df.to_csv("../submissions/lgbm_submission.csv", index=False)